import { useEffect, useState } from 'react';
import type { PredictResponse } from '../types';

interface ResultCardProps {
  result: PredictResponse;
}

const ResultCard = ({ result }: ResultCardProps) => {
  const isPlaced = result.prediction.toLowerCase().includes('placed') &&
    !result.prediction.toLowerCase().includes('not');

  const [barWidth, setBarWidth] = useState(0);

  // Animate confidence bar after mount
  useEffect(() => {
    const timer = setTimeout(() => setBarWidth(result.confidence), 80);
    return () => clearTimeout(timer);
  }, [result.confidence]);

  return (
    <div
      className={`glass-card result-enter ${isPlaced ? 'result-placed' : 'result-not-placed'}`}
      style={{ padding: '2rem' }}
      role="region"
      aria-label="Prediction result"
      aria-live="polite"
    >
      {/* Header ─────────────────────────────────────────────────── */}
      <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: '1rem', marginBottom: '1.5rem' }}>
        <div>
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', marginBottom: '0.5rem' }}>
            <span
              style={{ fontSize: '2rem' }}
              role="img"
              aria-label={isPlaced ? 'Success' : 'Not placed'}
            >
              {isPlaced ? '🎉' : '📋'}
            </span>
            <h2 style={{ fontSize: '1.375rem', fontWeight: 800, letterSpacing: '-0.03em' }}>
              Prediction Result
            </h2>
          </div>

          <span
            className={`badge ${isPlaced ? 'badge-green' : 'badge-red'}`}
            aria-label={`Status: ${result.prediction}`}
          >
            <span
              style={{
                width: 7, height: 7, borderRadius: '50%',
                background: isPlaced ? '#48bb78' : '#fc8181',
                flexShrink: 0,
              }}
              aria-hidden="true"
            />
            {result.prediction}
          </span>
        </div>

        {/* Confidence circle */}
        <div style={{ textAlign: 'center', flexShrink: 0 }}>
          <div
            style={{
              fontSize: '2rem',
              fontWeight: 900,
              letterSpacing: '-0.04em',
              color: isPlaced ? '#48bb78' : '#fc8181',
              lineHeight: 1,
            }}
            aria-label={`Confidence: ${result.confidence.toFixed(1)} percent`}
          >
            {result.confidence.toFixed(1)}
            <span style={{ fontSize: '1rem', fontWeight: 600 }}>%</span>
          </div>
          <div style={{ fontSize: '0.6875rem', color: 'var(--text-muted)', marginTop: '0.25rem', fontWeight: 600, letterSpacing: '0.06em', textTransform: 'uppercase' }}>
            Confidence
          </div>
        </div>
      </div>

      {/* Confidence bar ─────────────────────────────────────────── */}
      <div style={{ marginBottom: '1.5rem' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '0.5rem' }}>
          <span style={{ fontSize: '0.8125rem', color: 'var(--text-muted)', fontWeight: 500 }}>
            Model Confidence
          </span>
          <span style={{ fontSize: '0.8125rem', fontWeight: 700, color: isPlaced ? '#48bb78' : '#fc8181' }}>
            {result.confidence.toFixed(1)}%
          </span>
        </div>
        <div
          className="confidence-bar-track"
          role="progressbar"
          aria-valuenow={result.confidence}
          aria-valuemin={0}
          aria-valuemax={100}
          aria-label="Confidence level"
        >
          <div
            className={`confidence-bar-fill ${isPlaced ? 'confidence-bar-placed' : 'confidence-bar-not-placed'}`}
            style={{ width: `${barWidth}%` }}
          />
        </div>
      </div>

      {/* Divider */}
      <div className="divider" />

      {/* Message ─────────────────────────────────────────────────── */}
      <div
        style={{
          padding: '1.25rem',
          background: isPlaced
            ? 'rgba(72, 187, 120, 0.07)'
            : 'rgba(252, 129, 129, 0.06)',
          border: `1px solid ${isPlaced ? 'rgba(72, 187, 120, 0.2)' : 'rgba(252, 129, 129, 0.18)'}`,
          borderRadius: '0.875rem',
        }}
        role="note"
        aria-label="Personalised insight"
      >
        <p style={{ fontSize: '0.9375rem', lineHeight: 1.7, color: 'var(--text-secondary)' }}>
          <strong style={{ color: 'var(--text-primary)' }}>💡 Insight: </strong>
          {result.message}
        </p>
      </div>

      {/* Footer note */}
      <p
        style={{ fontSize: '0.75rem', color: 'var(--text-muted)', marginTop: '1.25rem', lineHeight: 1.6 }}
        aria-label="Disclaimer"
      >
        This prediction is generated by an ML model trained on historical campus placement data.
        It is intended for guidance only and does not guarantee actual placement outcomes.
      </p>
    </div>
  );
};

export default ResultCard;
